[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.18"
evm_version = "shanghai"

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
fuji = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/43113/etherscan", chain = "fuji" }
