[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']

solc = "0.8.19"
evm_version = "shanghai"


[fmt]
line_length = 100

[rpc_endpoints]
localhost = "http://localhost:9650/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
fuji = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/43113/etherscan", chain = "fuji" }
